"""Curated cultural intelligence pre-seeded for Lisbon, Porto, and Bragança."""
from typing import List, Dict, Any

PRESEEDED_ITEMS: Dict[str, List[Dict[str, Any]]] = {
    "Lisbon": [
        {
            "title": "Pastéis de Belém (Since 1837)",
            "category": "dining",
            "neighborhood": "Belém",
            "address": "Rua de Belém 84-92, 1300-085 Lisboa",
            "lat": 38.6975,
            "lon": -9.2032,
            "cost": "€1.50 - €5",
            "is_free": False,
            "time_info": "8:00 AM - 9:00 PM Daily",
            "highlight": "Original secret custard tart recipe direct from Jerónimos Monastery.",
            "description": "The birthplace of the Portuguese pastel de nata. Enjoy fresh, warm tarts dusted with cinnamon alongside a strong bica espresso in tile-lined salon rooms.",
            "source_platform": "Lonely Planet",
            "url": "https://pasteisdebelem.pt"
        },
        {
            "title": "Clube de Fado (Alfama)",
            "category": "music",
            "neighborhood": "Alfama",
            "address": "Rua de São João da Praça 86, 1100-521 Lisboa",
            "lat": 38.7114,
            "lon": -9.1306,
            "cost": "€35 - €60 (Dinner & Show)",
            "is_free": False,
            "time_info": "8:00 PM - 1:00 AM (Reservations Essential)",
            "highlight": "Haunting traditional Fado beneath 12th-century stone arches next to Lisbon Cathedral.",
            "description": "Renowned for elite fadistas accompanied by Portuguese 12-string guitar. Atmospheric stone arches and candlelight create an unforgettable cultural evening.",
            "source_platform": "TimeOut Lisbon",
            "url": "https://www.clube-de-fado.com"
        },
        {
            "title": "Miradouro de Santa Luzia & Portas do Sol",
            "category": "outdoors",
            "neighborhood": "Alfama",
            "address": "Largo Santa Luzia, 1100-487 Lisboa",
            "lat": 38.7117,
            "lon": -9.1303,
            "cost": "Free",
            "is_free": True,
            "time_info": "Open 24/7 (Best at Sunset)",
            "highlight": "Bougainvillea-draped terrace overlooking red-tile rooftops and the Tagus River.",
            "description": "Stunning tiled azulejo balcony depicting pre-1755 earthquake Lisbon. Street guitarists and warm sunset breezes make this one of Europe's top viewpoints.",
            "source_platform": "Reddit r/lisboa",
            "url": "https://www.visitlisboa.com"
        },
        {
            "title": "Calouste Gulbenkian Museum & Modern Art Center",
            "category": "historic",
            "neighborhood": "Avenidas Novas",
            "address": "Av. de Berna 45A, 1067-001 Lisboa",
            "lat": 38.7375,
            "lon": -9.1540,
            "cost": "€10 (Free Sundays after 2 PM)",
            "is_free": False,
            "time_info": "10:00 AM - 6:00 PM (Closed Tuesdays)",
            "highlight": "One of the world's greatest private collections: Egyptian relics, Rembrandt, and Lalique jewelry.",
            "description": "Surrounded by lush modernist gardens with ponds and amphitheaters. A peaceful retreat with incredible ancient Greco-Roman, Islamic, and European masterworks.",
            "source_platform": "Guides",
            "url": "https://gulbenkian.pt/museu"
        },
        {
            "title": "LX Factory & Ler Devagar Bookstore",
            "category": "gems",
            "neighborhood": "Alcântara",
            "address": "R. Rodrigues de Faria 103, 1300-501 Lisboa",
            "lat": 38.7037,
            "lon": -9.1789,
            "cost": "Free admission",
            "is_free": True,
            "time_info": "10:00 AM - Midnight",
            "highlight": "Repurposed 19th-century textile factory with giant bookstore and rooftop bars.",
            "description": "Creative cultural island tucked beneath the 25 de Abril Bridge. Home to art studios, indie vinyl bins, artisan craft markets, and Ler Devagar's soaring book wall.",
            "source_platform": "TikTok Trends",
            "url": "https://lxfactory.com"
        },
        {
            "title": "Cervejaria Ramiro (Legendary Seafood Saloon)",
            "category": "dining",
            "neighborhood": "Intendente",
            "address": "Av. Almirante Reis 1, 1150-038 Lisboa",
            "lat": 38.7203,
            "lon": -9.1350,
            "cost": "€35 - €70",
            "is_free": False,
            "time_info": "12:00 PM - Midnight (Closed Mondays)",
            "highlight": "Anthony Bourdain's favorite garlic tiger prawns and steak sandwich prego dessert.",
            "description": "High-energy temple of shellfish. Order scarlet giant prawns, percebes (goose barnacles), buttery toasted bread, and finish with their signature beef prego sandwich.",
            "source_platform": "Eater",
            "url": "https://www.cervejariaramiro.pt"
        }
    ],
    "Porto": [
        {
            "title": "Livraria Lello (Historic Neo-Gothic Bookstore)",
            "category": "historic",
            "neighborhood": "Vitória / Clérigos",
            "address": "R. das Carmelitas 144, 4050-161 Porto",
            "lat": 41.1468,
            "lon": -8.6148,
            "cost": "€8 (Deductible against book purchase)",
            "is_free": False,
            "time_info": "9:30 AM - 7:00 PM (Timed Entry Required)",
            "highlight": "Famous crimson winding staircase and stained glass ceiling operating since 1906.",
            "description": "Ranked among the most beautiful bookstores in the world. Stunning carved wood details, soaring glass roof, and literary heritage in the heart of Porto.",
            "source_platform": "Fodor's",
            "url": "https://www.livrarialello.pt"
        },
        {
            "title": "Taylor's Port Wine Cellars & Tasting Lodges",
            "category": "wine",
            "neighborhood": "Vila Nova de Gaia",
            "address": "Rua do Choupelo 250, 4400-088 Vila Nova de Gaia",
            "lat": 41.1338,
            "lon": -8.6142,
            "cost": "€15 - €35 (Tasting Included)",
            "is_free": False,
            "time_info": "10:00 AM - 7:30 PM Daily",
            "highlight": "Centuries-old oak vats aging rare Tawny Port, paired with panoramic Douro views.",
            "description": "Founded in 1692. Audio tour through cavernous cellars, tasting of Chip Dry white port and aged 20-year tawnies, complemented by resident peacocks in the garden.",
            "source_platform": "Guides",
            "url": "https://www.taylor.pt"
        },
        {
            "title": "Ribeira Promenade & Dom Luís I Bridge Walk",
            "category": "outdoors",
            "neighborhood": "Ribeira",
            "address": "Praça da Ribeira, 4050-513 Porto",
            "lat": 41.1406,
            "lon": -8.6128,
            "cost": "Free",
            "is_free": True,
            "time_info": "Open 24/7",
            "highlight": "Walk across the upper span of Eiffel's double-deck iron bridge over the Douro.",
            "description": "Cobblestone riverfront lined with colorful pastel row houses, street performers, and traditional wooden rabelo boats bobbing along the water.",
            "source_platform": "Lonely Planet",
            "url": "https://visitporto.travel"
        },
        {
            "title": "Serralves Museum of Contemporary Art & Park",
            "category": "historic",
            "neighborhood": "Lordelo do Ouro",
            "address": "Rua Dom João de Castro 210, 4150-417 Porto",
            "lat": 41.1594,
            "lon": -8.6596,
            "cost": "€20 (Park + Museum)",
            "is_free": False,
            "time_info": "10:00 AM - 7:00 PM Daily",
            "highlight": "Álvaro Siza Vieira designed museum and treetop walkway through lush Art Deco gardens.",
            "description": "World-class contemporary exhibits set inside an 18-hectare estate featuring a pink Art Deco villa, modern sculpture lawns, and an elevated canopy walk.",
            "source_platform": "TimeOut Porto",
            "url": "https://www.serralves.pt"
        },
        {
            "title": "Cervejaria Gazela (Original Cachorrinho)",
            "category": "dining",
            "neighborhood": "Batalha",
            "address": "Travessa Cimo de Vila 4, 4000-171 Porto",
            "lat": 41.1448,
            "lon": -8.6067,
            "cost": "€4 - €8",
            "is_free": False,
            "time_info": "12:00 PM - 10:30 PM (Closed Sundays)",
            "highlight": "Crispy toasted spicy sausage sandwich with melted cheese cut into bite-sized strips.",
            "description": "Beloved by locals and world chefs. Order the spicy cachorrinho paired with an ice-cold Super Bock craft draft at the horseshoe bar.",
            "source_platform": "Reddit r/porto",
            "url": "https://cervejariagazela.pt"
        }
    ],
    "Bragança": [
        {
            "title": "Castelo de Bragança & Medieval Citadel",
            "category": "historic",
            "neighborhood": "Cidadela Histórica",
            "address": "Rua do Santo Condestável, 5300-025 Bragança",
            "lat": 41.8042,
            "lon": -6.7503,
            "cost": "€2 - €3 (Citadel Grounds Free)",
            "is_free": False,
            "time_info": "9:00 AM - 5:00 PM",
            "highlight": "12th-century military keep known as Torre de Menagem with 15 intact watchtowers.",
            "description": "Spectacular fortress overlooking Trás-os-Montes. Walk along the ancient crenellated stone walls and explore the Military Museum housed inside the 33-meter keep.",
            "source_platform": "Guides",
            "url": "https://www.turismodocentro.pt"
        },
        {
            "title": "Domus Municipalis (Romanesque Town Hall)",
            "category": "historic",
            "neighborhood": "Cidadela Histórica",
            "address": "Cidadela de Bragança, 5300-025 Bragança",
            "lat": 41.8039,
            "lon": -6.7495,
            "cost": "Free",
            "is_free": True,
            "time_info": "10:00 AM - 5:00 PM",
            "highlight": "The only surviving Romanesque civic building in the Iberian Peninsula.",
            "description": "Unique pentagonal stone building built over a natural cistern that served as a medieval council chamber and water reservoir. An architectural rarity in Europe.",
            "source_platform": "Lonely Planet",
            "url": "https://cm-braganca.pt"
        },
        {
            "title": "Restaurante Solar Bragançano",
            "category": "dining",
            "neighborhood": "Centro Histórico",
            "address": "Praça da Sé 34, 5300-265 Bragança",
            "lat": 41.8062,
            "lon": -6.7554,
            "cost": "€25 - €45",
            "is_free": False,
            "time_info": "12:30 PM - 3:00 PM, 7:30 PM - 10:00 PM",
            "highlight": "Posta Mirandesa (fire-grilled veal steak) in an antique 18th-century noble manor.",
            "description": "Authentic regional Trás-os-Montes gastronomy. Enjoy wild boar with chestnuts, game dishes, and tender Posta Mirandesa accompanied by full-bodied Douro and Trás-os-Montes wines.",
            "source_platform": "Eater / Michelin Guide",
            "url": "https://solarbragancano.pt"
        },
        {
            "title": "Montesinho Natural Park Trail (Serra da Coroa)",
            "category": "outdoors",
            "neighborhood": "Montesinho",
            "address": "Parque Natural de Montesinho, Bragança",
            "lat": 41.9360,
            "lon": -6.8500,
            "cost": "Free",
            "is_free": True,
            "time_info": "Daylight hours",
            "highlight": "Wild granite mountain trails home to the Iberian wolf and preserved slate villages.",
            "description": "One of Portugal's largest and wild-preserved nature reserves. Hike among ancient chestnut forests, rushing granite streams, and slate-roof hamlets like Rio de Onor.",
            "source_platform": "Reddit r/portugal",
            "url": "https://icnf.pt"
        },
        {
            "title": "Museu Ibérico da Máscara e do Traje",
            "category": "gems",
            "neighborhood": "Cidadela",
            "address": "Rua D. Fernão o Bravo 24, 5300-025 Bragança",
            "lat": 41.8035,
            "lon": -6.7498,
            "cost": "€1 (Very affordable)",
            "is_free": False,
            "time_info": "10:00 AM - 6:00 PM (Closed Mondays)",
            "highlight": "Fascinating pagan Caretos festival masks crafted from brass, wood, and wool.",
            "description": "Celebrates the ancient winter solstice rituals and devilish Caretos characters of northeastern Portugal and neighboring Spanish Zamora. A deeply unique ethnographic treasure.",
            "source_platform": "TimeOut",
            "url": "https://cm-braganca.pt"
        }
    ],
    "Washington, D.C.": [
        {
            "title": "National Cherry Blossom Festival & Tidal Basin Walk",
            "category": "outdoors",
            "neighborhood": "National Mall & Tidal Basin",
            "address": "Tidal Basin, Washington, DC 20024",
            "lat": 38.8853,
            "lon": -77.0386,
            "cost": "Free",
            "is_free": True,
            "time_info": "Open 24/7 (Best at Sunrise/Sunset)",
            "highlight": "3,000+ Yoshino and Kwanzan cherry blossom trees in peak bloom along the water.",
            "description": "The quintessential Washington spring experience. Stroll the 2.1-mile pedestrian path encircling the Tidal Basin with framing views of the Jefferson and MLK Memorials.",
            "source_platform": "Curated",
            "url": "https://nationalcherryblossomfestival.org"
        },
        {
            "title": "Lincoln Memorial & Reflecting Pool",
            "category": "historic",
            "neighborhood": "National Mall",
            "address": "2 Lincoln Memorial Cir NW, Washington, DC 20002",
            "lat": 38.8893,
            "lon": -77.0502,
            "cost": "Free",
            "is_free": True,
            "time_info": "Open 24 Hours (Rangers on duty 9:30 AM - 10:00 PM)",
            "highlight": "Colossal 19-foot Daniel Chester French statue of Lincoln looking down the 2,000-ft Reflecting Pool.",
            "description": "Ionic neoclassical temple commemorating the 16th U.S. President. The steps are the historic site of Martin Luther King Jr.'s 1963 'I Have a Dream' address.",
            "source_platform": "National Park Service",
            "url": "https://nps.gov/linc"
        },
        {
            "title": "Ben's Chili Bowl (U Street)",
            "category": "dining",
            "neighborhood": "U Street Corridor",
            "address": "1213 U St NW, Washington, DC 20009",
            "lat": 38.9169,
            "lon": -77.0287,
            "cost": "$10 - $18",
            "is_free": False,
            "time_info": "11:00 AM - 11:00 PM (Late-night weekends)",
            "highlight": "Original Chili Half-Smoke sausage on a steamed bun topped with homemade spicy chili con carne.",
            "description": "D.C. civil rights landmark and culinary institution since 1958. Visited by Duke Ellington, Miles Davis, and Barack Obama.",
            "source_platform": "Eater DC",
            "url": "https://benschilibowl.com"
        },
        {
            "title": "Library of Congress (Thomas Jefferson Building)",
            "category": "historic",
            "neighborhood": "Capitol Hill",
            "address": "10 1st St SE, Washington, DC 20540",
            "lat": 38.8887,
            "lon": -77.0047,
            "cost": "Free (Timed-entry pass required)",
            "is_free": True,
            "time_info": "10:00 AM - 5:00 PM (Closed Sundays)",
            "highlight": "Gilded Italian Renaissance Great Hall and the octagonal Main Reading Room overlook.",
            "description": "The largest library in the world and one of the finest architectural achievements in America. Displays include the 1455 Gutenberg Bible and Thomas Jefferson's original library.",
            "source_platform": "Curated",
            "url": "https://loc.gov/visit"
        },
        {
            "title": "Blues Alley Jazz Club",
            "category": "music",
            "neighborhood": "Georgetown",
            "address": "1073 Wisconsin Ave NW, Washington, DC 20007",
            "lat": 38.9038,
            "lon": -77.0628,
            "cost": "$30 - $65 + $15 min food/drink",
            "is_free": False,
            "time_info": "Shows at 7:00 PM & 9:00 PM nightly",
            "highlight": "Intimate 125-seat red brick carriage house operating continuously since 1965.",
            "description": "America's oldest continuing jazz supper club. Legends who recorded live albums here include Dizzy Gillespie, Sarah Vaughan, and Eva Cassidy.",
            "source_platform": "TimeOut DC",
            "url": "https://bluesalley.com"
        },
        {
            "title": "National Museum of African American History and Culture",
            "category": "historic",
            "neighborhood": "National Mall",
            "address": "1400 Constitution Ave NW, Washington, DC 20560",
            "lat": 38.8911,
            "lon": -77.0326,
            "cost": "Free (Free timed-entry pass required online)",
            "is_free": True,
            "time_info": "10:00 AM - 5:30 PM Daily",
            "highlight": "Corona-shaped bronze architectural lattice and underground History Galleries ascending from 1400 to today.",
            "description": "The only national museum devoted exclusively to the African American life, history, and culture. Moving exhibits include Harriet Tubman's hymnal and Chuck Berry's red Cadillac.",
            "source_platform": "Smithsonian",
            "url": "https://nmaahc.si.edu"
        },
        {
            "title": "Old Ebbitt Grill (Since 1856)",
            "category": "dining",
            "neighborhood": "Downtown / Penn Quarter",
            "address": "675 15th St NW, Washington, DC 20005",
            "lat": 38.8979,
            "lon": -77.0337,
            "cost": "$25 - $55 (Half-price Oyster Hour: 3-5pm & 11pm-close)",
            "is_free": False,
            "time_info": "8:00 AM - 2:00 AM Daily",
            "highlight": "Washington's oldest saloon, steps from the White House, famous for the legendary Oyster Bar.",
            "description": "Historic Victorian mahogany tavern favored by presidents from Grant and Cleveland to modern diplomats. Renowned for raw oysters and jumbo lump crab cakes.",
            "source_platform": "Guides",
            "url": "https://ebbitt.com"
        },
        {
            "title": "Eastern Market Weekend Flea & Farmers Market",
            "category": "gems",
            "neighborhood": "Capitol Hill",
            "address": "225 7th St SE, Washington, DC 20003",
            "lat": 38.8845,
            "lon": -76.9958,
            "cost": "Free admission",
            "is_free": True,
            "time_info": "9:00 AM - 4:00 PM (Saturdays & Sundays)",
            "highlight": "Historic 1873 brick South Hall with local cheesemongers, artists, and live buskers.",
            "description": "The heartbeat of Capitol Hill for over 150 years. Browse open-air artist tents, artisan jewelry, vintage books, and grab famous blueberry buckwheat pancakes at Market Lunch.",
            "source_platform": "Reddit r/washingtondc",
            "url": "https://easternmarket-dc.org"
        }
    ]
}

